### ISSUE TITLE
Update yay to 12.4.2

### ISSUE THREAD

**Issue by justbispo** [fsquillace/junest-repo#1]
Hi, yay needs to be updated in this repository. With the release of pacman 7, yay needs to be rebuilt so it can work with the new version of libalpm.
Right now, on a new installation, if you try to run yay it returns:
```
yay: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory
```

**Comment by fsquillace** [comment]
Thanks for the headsup. I updated the junest image which now includes the latest version of pacman 7 and yay.
